/**
 * Stand-in snapshot used when `data/models.json` has not been produced yet.
 *
 * The twelve records are chosen to exercise every branch of the attribute →
 * layer mapping: all five size tiers, all five price tiers, gold/laurel/silver
 * crowns plus unranked, fresh, retired, opaque parameters, and each capability
 * flag in both states. Three of them share the `openai` vendor so the family
 * resemblance is visible in the contact sheet.
 */

import type { ModelRecord, SourceId, Vendor, WorldSnapshot } from '../../src/lib/types.ts';

type Sparse = Partial<ModelRecord> & Pick<ModelRecord, 'id' | 'name' | 'vendorId'>;

function model(m: Sparse): ModelRecord {
  return {
    slug: m.id.replace(/[^a-z0-9]+/gi, '-').toLowerCase(),
    releaseDate: null,
    releaseDatePrecision: 'day',
    knowledgeCutoff: null,
    retiredAt: null,
    contextWindow: null,
    maxOutput: null,
    pricing: { inputPerMTok: null, outputPerMTok: null, cachedInputPerMTok: null },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { toolCall: null, reasoning: null, structuredOutput: null, promptCaching: null },
    openWeights: null,
    license: null,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: {
      eci: null,
      swe_bench_verified: null,
swe_bench_vendor: null,
swe_bench_pro: null,
      aime: null,
      gpqa_diamond: null,
      arc_agi_2: null,
      fiction_live: null,
      webdev_arena_elo: null,
    },
    provenance: {},
    firstSeenAt: '2026-08-31',
    ...m,
  } as ModelRecord;
}

const VENDORS: Vendor[] = [
  { id: 'openai', name: 'OpenAI', nameZh: 'OpenAI', country: 'US', continent: 'west', motif: 'scholar', accentColor: '#10A37F', homepage: 'https://openai.com' },
  { id: 'anthropic', name: 'Anthropic', nameZh: 'Anthropic', country: 'US', continent: 'west', motif: 'sage', accentColor: '#D97757', homepage: 'https://anthropic.com' },
  { id: 'google', name: 'Google DeepMind', nameZh: '谷歌', country: 'US', continent: 'west', motif: 'oracle', accentColor: '#4285F4', homepage: 'https://deepmind.google' },
  { id: 'meta', name: 'Meta', nameZh: 'Meta', country: 'US', continent: 'west', motif: 'llama', accentColor: '#0064E0', homepage: 'https://ai.meta.com' },
  { id: 'xai', name: 'xAI', nameZh: 'xAI', country: 'US', continent: 'west', motif: 'nebula', accentColor: '#1A1A1A', homepage: 'https://x.ai' },
  { id: 'mistral', name: 'Mistral AI', nameZh: 'Mistral', country: 'FR', continent: 'west', motif: 'wind', accentColor: '#FF7000', homepage: 'https://mistral.ai' },
  { id: 'deepseek', name: 'DeepSeek', nameZh: '深度求索', country: 'CN', continent: 'east', motif: 'whale', accentColor: '#4D6BFE', homepage: 'https://deepseek.com' },
  { id: 'alibaba', name: 'Alibaba Qwen', nameZh: '阿里通义千问', country: 'CN', continent: 'east', motif: 'qilin', accentColor: '#615CED', homepage: 'https://qwen.ai' },
  { id: 'moonshot', name: 'Moonshot AI', nameZh: '月之暗面', country: 'CN', continent: 'east', motif: 'lunar', accentColor: '#2B2B45', homepage: 'https://moonshot.cn' },
  { id: 'zhipu', name: 'Zhipu AI', nameZh: '智谱', country: 'CN', continent: 'east', motif: 'scribe', accentColor: '#3859FF', homepage: 'https://zhipuai.cn' },
];

const MODELS: ModelRecord[] = [
  model({
    id: 'openai/gpt-5.3',
    name: 'GPT-5.3',
    vendorId: 'openai',
    releaseDate: '2026-05-14',
    contextWindow: 400_000,
    pricing: { inputPerMTok: 15, outputPerMTok: 60, cachedInputPerMTok: 1.5 },
    modalities: { input: ['text', 'image', 'audio', 'pdf'], output: ['text', 'audio'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: true },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: { eci: 152, swe_bench_verified: 79, swe_bench_vendor: null, swe_bench_pro: null, aime: 96, gpqa_diamond: 89, arc_agi_2: 31, fiction_live: 82, webdev_arena_elo: 1420 },
  }),
  model({
    id: 'openai/gpt-5.3-mini',
    name: 'GPT-5.3 mini',
    vendorId: 'openai',
    releaseDate: '2026-05-14',
    contextWindow: 400_000,
    pricing: { inputPerMTok: 0.2, outputPerMTok: 0.8, cachedInputPerMTok: 0.02 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: false, structuredOutput: true, promptCaching: true },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: { eci: 128, swe_bench_verified: 61, swe_bench_vendor: null, swe_bench_pro: null, aime: 82, gpqa_diamond: 71, arc_agi_2: 9, fiction_live: 58, webdev_arena_elo: 1240 },
  }),
  model({
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    vendorId: 'openai',
    releaseDate: '2024-05-13',
    retiredAt: '2026-07-01',
    contextWindow: 128_000,
    pricing: { inputPerMTok: 2.5, outputPerMTok: 5, cachedInputPerMTok: 1.25 },
    modalities: { input: ['text', 'image', 'audio'], output: ['text', 'audio'] },
    capabilities: { toolCall: true, reasoning: false, structuredOutput: true, promptCaching: true },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
  }),
  model({
    id: 'anthropic/claude-opus-4.9',
    name: 'Claude Opus 4.9',
    vendorId: 'anthropic',
    releaseDate: '2026-08-20',
    contextWindow: 1_000_000,
    pricing: { inputPerMTok: 15, outputPerMTok: 75, cachedInputPerMTok: 1.5 },
    modalities: { input: ['text', 'image', 'pdf'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: true },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: { eci: 150, swe_bench_verified: 82, swe_bench_vendor: null, swe_bench_pro: null, aime: 94, gpqa_diamond: 88, arc_agi_2: 27, fiction_live: 80, webdev_arena_elo: 1455 },
  }),
  model({
    id: 'google/gemini-3.2-pro',
    name: 'Gemini 3.2 Pro',
    vendorId: 'google',
    releaseDate: '2026-06-02',
    contextWindow: 2_000_000,
    pricing: { inputPerMTok: 2.5, outputPerMTok: 12, cachedInputPerMTok: 0.3 },
    modalities: { input: ['text', 'image', 'audio', 'video', 'pdf'], output: ['text', 'image'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: true },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: { eci: 149, swe_bench_verified: 76, swe_bench_vendor: null, swe_bench_pro: null, aime: 95, gpqa_diamond: 90, arc_agi_2: 25, fiction_live: 91, webdev_arena_elo: 1400 },
  }),
  model({
    id: 'xai/grok-5',
    name: 'Grok 5',
    vendorId: 'xai',
    releaseDate: '2026-08-11',
    contextWindow: 1_000_000,
    pricing: { inputPerMTok: 3, outputPerMTok: 15, cachedInputPerMTok: 0.75 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: false },
    openWeights: false,
    params: { totalB: null, activeB: null, confidence: 'unknown' },
    benchmarks: { eci: 147, swe_bench_verified: 74, swe_bench_vendor: null, swe_bench_pro: null, aime: 93, gpqa_diamond: 87, arc_agi_2: 22, fiction_live: 66, webdev_arena_elo: 1385 },
  }),
  model({
    id: 'deepseek/deepseek-v4',
    name: 'DeepSeek V4',
    vendorId: 'deepseek',
    releaseDate: '2026-03-24',
    contextWindow: 256_000,
    pricing: { inputPerMTok: 0.28, outputPerMTok: 0.42, cachedInputPerMTok: 0.028 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: true },
    openWeights: true,
    license: 'MIT',
    params: { totalB: 671, activeB: 37, confidence: 'exact' },
    benchmarks: { eci: 145, swe_bench_verified: 70, swe_bench_vendor: null, swe_bench_pro: null, aime: 92, gpqa_diamond: 84, arc_agi_2: 17, fiction_live: 61, webdev_arena_elo: 1330 },
  }),
  model({
    id: 'moonshot/kimi-k3',
    name: 'Kimi K3',
    vendorId: 'moonshot',
    releaseDate: '2026-08-25',
    contextWindow: 256_000,
    pricing: { inputPerMTok: 0.6, outputPerMTok: 2.5, cachedInputPerMTok: 0.15 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: true, structuredOutput: true, promptCaching: true },
    openWeights: true,
    license: 'Apache-2.0',
    params: { totalB: 1200, activeB: 42, confidence: 'exact' },
    benchmarks: { eci: 141, swe_bench_verified: 71, swe_bench_vendor: null, swe_bench_pro: null, aime: 90, gpqa_diamond: 82, arc_agi_2: 14, fiction_live: 59, webdev_arena_elo: 1305 },
  }),
  model({
    id: 'meta/llama-5-405b',
    name: 'Llama 5 405B',
    vendorId: 'meta',
    releaseDate: '2026-02-10',
    contextWindow: 256_000,
    pricing: { inputPerMTok: 0.25, outputPerMTok: 0.5, cachedInputPerMTok: null },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: false, structuredOutput: true, promptCaching: false },
    openWeights: true,
    license: 'LLAMA-5-Community',
    params: { totalB: 405, activeB: 405, confidence: 'exact' },
    benchmarks: { eci: 133, swe_bench_verified: 58, swe_bench_vendor: null, swe_bench_pro: null, aime: 79, gpqa_diamond: 72, arc_agi_2: 8, fiction_live: 47, webdev_arena_elo: 1255 },
  }),
  model({
    id: 'alibaba/qwen4-72b',
    name: 'Qwen4 72B',
    vendorId: 'alibaba',
    releaseDate: '2026-04-18',
    contextWindow: 1_000_000,
    pricing: { inputPerMTok: 0.4, outputPerMTok: 1.2, cachedInputPerMTok: 0.08 },
    modalities: { input: ['text', 'image'], output: ['text', 'image'] },
    capabilities: { toolCall: true, reasoning: false, structuredOutput: true, promptCaching: true },
    openWeights: true,
    license: 'Apache-2.0',
    params: { totalB: 72, activeB: 72, confidence: 'exact' },
    benchmarks: { eci: 121, swe_bench_verified: 52, swe_bench_vendor: null, swe_bench_pro: null, aime: 74, gpqa_diamond: 66, arc_agi_2: 6, fiction_live: 44, webdev_arena_elo: 1210 },
  }),
  model({
    id: 'zhipu/glm-6-air',
    name: 'GLM-6 Air',
    vendorId: 'zhipu',
    releaseDate: '2026-08-28',
    contextWindow: 200_000,
    pricing: { inputPerMTok: 0.06, outputPerMTok: 0.2, cachedInputPerMTok: null },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { toolCall: true, reasoning: false, structuredOutput: true, promptCaching: false },
    openWeights: true,
    license: 'MIT',
    params: { totalB: 9, activeB: 9, confidence: 'exact' },
    benchmarks: { eci: 112, swe_bench_verified: 39, swe_bench_vendor: null, swe_bench_pro: null, aime: 61, gpqa_diamond: 54, arc_agi_2: 3, fiction_live: 32, webdev_arena_elo: 1105 },
  }),
  model({
    id: 'mistral/mistral-small-4',
    name: 'Mistral Small 4',
    vendorId: 'mistral',
    releaseDate: '2026-01-09',
    contextWindow: 128_000,
    pricing: { inputPerMTok: 0.1, outputPerMTok: 0.3, cachedInputPerMTok: null },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { toolCall: false, reasoning: false, structuredOutput: true, promptCaching: false },
    openWeights: true,
    license: 'Apache-2.0',
    params: { totalB: 24, activeB: 24, confidence: 'exact' },
  }),
];

export function mockSnapshot(): WorldSnapshot {
  const sources = Object.fromEntries(
    (['models.dev', 'epoch.ai', 'huggingface', 'openrouter', 'vercel-gateway', 'litellm', 'derived', 'override'] as SourceId[]).map(
      (id) => [id, { ok: false, fetchedAt: null, note: 'mock snapshot' }],
    ),
  ) as WorldSnapshot['sources'];
  return { generatedAt: '2026-08-31T00:00:00.000Z', sources, vendors: VENDORS, models: MODELS };
}
